services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: duelpath
      POSTGRES_PASSWORD: duelpath
      POSTGRES_DB: duelpath
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
